### ISSUE TITLE
关于网站LOGO

### ISSUE THREAD

**Issue by Reedo0910** [fisheva/Eva-Blog#1]
你好，我是Velas (velas.xyz) 的网站作者，Velas的网站logo为我原创的设计。
![webapplogo](https://user-images.githubusercontent.com/19267441/50265216-8e88b580-03ec-11e9-8c37-cd81c4693c97.png)

今天偶然之间看到你的网站，发现你网站的logo以及favicon和我网站（velas.xyz）的logo与favicon实在太过相似。

<img width="559" alt="2018-12-19" src="https://user-images.githubusercontent.com/19267441/50265733-e6c0b700-03ee-11e9-9bad-7f6b343a5070.png">

我保有对该设计的著作权，我认为你对该设计的修改和使用不大妥当，甚至已涉及了侵权。

在此告知，望修改，谢谢。

**Comment by fisheva** [comment]
velas.xyz 作者您好!

很抱歉过了这么久才回复您, 因为这个个人网站项目被我搁置了几个月, 最近想重拾起, 才点开项目看到您留的issue。

在做个人网站前, 没有思路不知道如何设计自己的网站, 先在网上找优秀的同类网站, 看看别人是怎么做的, 我猜许多建站的人都经历过。

以下是我仿造您的设计风格, 设计自己网站LOGO的思路历程:

"fish" "鱼", 从上网之初给自己起网名起, 我就喜欢在网名里带这2个字。 所以在思考自己网站的LOGO时, 我想的也是如何设计一个具有"鱼"意像的LOGO。这个图标要像哪一种鱼吗?鲸鱼、鲤鱼、鲨鱼? 好像都不是, 我也从没把自己比作过任何一种具象的鱼, 我喜欢鱼这个意像, 好像就是喜欢它所代表的自由自在的感觉。所以LOGO设计思路又具象了点: 有"鱼"的意像, 但又不能具象成任何一种鱼。

在逛到您的网站, 看到您的网站LOGO时, 我确实深受启发, 在尾部多加一个△, 构成了一个有着鱼意像的图标, 而且因为沿用了您的设计风格, 非常简约, 时尚, 有设计感。

我承认这种设计风格是您原创发明的, 您用这种设计风格设计了一个△(抱歉尚未读懂您的立意), 我用这种设计风格设计了一条"鱼", 外在确实很相似, 仅仅是我的图标多了一个△, 可是要表达的主题内核已截然不同。请问用同种设计风格表达不同的东西 就构成侵权吗? 如果侵权, 那是否意味着, 这世上有多少名设计师, 就应该有多少种设计风格, 否则后来者都是侵权?

也许未来我会彻底改版LOGO, 但对这款LOGO我的处理结果是: 形保留, 颜色用彩色, 避开黑色icon 以免与您网站icon过于相似。

![image](https://user-images.githubusercontent.com/17448419/60072100-fd095000-974e-11e9-91e2-33dbbe53f04c.png)

这么做的原因不是我觉得黑色icon不可用, 真的侵权了, 而是我觉得无论是作为设计师还是程序员, 您能力都远超于我(一个设计转前端, 久久徘徊在前端门口的小菜鸡), 是我的前辈, 我不想与您交恶。未来哪天, 我这个个人小站真建成了, 我也会发一篇文章讲明网站LOGO的设计历程, 向每一个来访我小站的人讲明您的设计对这个网站LOGO成形的影响。希望我的做法您还满意。

**Comment by Reedo0910** [comment]
您好，首先我想说明我并无恶意。

我设计的logo结合了我的网站名的首字母V和“发送电波”的意象。因为当初设计时经过了多次修改和简化，因此它和“velas”这个名字一样，都对我意义非凡，相信做过设计的你也能体会这种感受。

我最初来访你的网站只是因为你在我网站上留了言，并且我发现你在GitHub上也关注了我。我一直很重视和尊敬我网站的来客，于是我抱着学习与交流的心态前来。而且，当我发现我曾经是你vscode主题的用户，并曾经在微信某个知乎前端群里就你的主题和你进行过交流时（可能你已经不记得了），我曾对此感到十分亲切。

而当我访问你的网站并看到那个logo时，当时我十分吃惊，但我并未因此立即发出这个issue。因为我当时是认为你喜欢这个设计，并以此为参考、延展出自己设计的图案。对此，我都曾报以最大的理解和善意。

直到后来，我发现你网站的某次更新使用了现在这个favicon，我无法再在感性上进行任何共情与善意的猜测。

![image](https://user-images.githubusercontent.com/19267441/60101658-bdfaef00-978e-11e9-8cd0-ac4e09c02435.png)

favicon经缩小了之后，这两者外形的差异实在太过微小，以致几乎失去了辨识度。再加上对此你并未与我有任何的接触与交流，而且你并未在网站中提及它的参考来源，我无法得知你的意图是善意的学习使用还是其他什么，因此去年我在气愤之下发出了这个issue。

现在我已了解了你的意图，所以我也提出我最低的要求：

1.在网站上提及这个Logo设计的灵感来源；

2.直到将这个Logo修改至有足够的辨识度前，不能将其用于商业用途。

[参考资料](https://www.uisdc.com/plagiarism-reference-copying-and-originality)

我理解你在学习过程中作出的尝试与努力。但我同样热爱着我的设计和作品，希望你能理解。

**Comment by fisheva** [comment]
**"这个Logo修改至有足够的辨识度"**: 在我改用彩色icon后, 让任何人来看, 外形能看出相似, 但区分度已足够明显, 我认为符合要求。

![image](https://user-images.githubusercontent.com/17448419/60152393-e4fb0480-9812-11e9-8855-f0ab8ab531b0.png)

**"在网站中提及这个Logo设计的灵感来源"**: 在我上一段回复里就提到了, 待网站建成, 我开始在这个网站上更新博文, 如果届时网站Logo还没改版, 我会写篇博文说明这个Logo设计的历程, 提及您的设计对这个Logo成形的影响。并且在Logo彻底改版前, 我会一直使用这个仓库更新网站, 即使issue关闭, 网友也可以查看关闭issue, 有迹可循的在这里看到这段历史。

**"不能将其用于商业用途"**: 这个网站我想做的就是 写写博文, 发发随想, 展示自己的作品, 分享些自己喜欢的东西, 顺便可以在自己的网站代码中尝试任何自己喜欢的技术。功能应该是和您的网站, 和所有个人博客是相似的, 并没有任何商业用途的计划。

**Comment by Reedo0910** [comment]
好的，谢谢你的理解。
